name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install shiv
        run: |
          uv sync --locked --only-dev

      - name: Install dependencies
        run: |
          pip install -r <(uv export --no-dev --no-hashes) --target dist/

      - name: Get Version
        id: version_info
        run: |
          echo "version=$(uv run setuptools-scm)" >> $GITHUB_OUTPUT
      
      - name: Build app bundle
        run: |
          #cp -r bot dist/
          uv run shiv --site-packages dist --compressed --compile-pyc -o bot-${{ steps.version_info.outputs.version }}.pyz -e bot.main:main

      - name: Upload API artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-${{ steps.version_info.outputs.version }}.pyz
          path: bot-${{ steps.version_info.outputs.version }}.pyz

